FROM node:12.8.0-alpine AS build
LABEL maintainer="rosalesvictor.dev@gmail.com"
WORKDIR /client
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:12.8.0-alpine
RUN npm install -g serve
COPY --from=build /client/build /client
EXPOSE 3000
CMD serve -s /client -l 3000