version: '3'
services:
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        container_name: react-django-server-dev
        env_file: ./server/.env
        environment:
        - PYTHONUNBUFFERED=1
        entrypoint:
        - sh
        - /server/run.sh
        ports:
        - "3000:3000"
        volumes:
        - ./server:/server
    client:
        stdin_open: true
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        ports: 
            - 3001:3001
        volumes:
            - ./client/src:/client/src
        container_name: react-django-client-dev
        depends_on:
            - server