version: '3'
services:
    client:
        build: ./client
        ports: 
            - 3000:3000
        container_name: react-express-client-prod
        depends_on:
            - server
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        env_file: ./server/.env
        environment:
            - PYTHONUNBUFFERED=1
        ports:
            - 5000:5000
        volumes:
            - .:/server
        container_name: react-django-server-dev
